language: node_js
node_js:
  - "stable"
  - node
env:
  - $DATABASE_URL
cache:
  directories:
    - "node_modules"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"sherren", pwd:"test", roles:["readWrite"]});'
